import React from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./ui/card";
import { Bot, FileText, ChevronRight } from "lucide-react";

interface SummaryCardProps {
    bullets: string[];
    rawSummary: string;
    modelUsed: string;
}

export function SummaryCard({ bullets, rawSummary, modelUsed }: SummaryCardProps) {
    if (!bullets || bullets.length === 0) {
        return null;
    }

    return (
        <Card className="w-full h-full shadow-sm hover:shadow transition-shadow">
            <CardHeader className="bg-slate-50 border-b pb-4 rounded-t-xl">
                <div className="flex items-center gap-2">
                    <div className="p-2 bg-blue-100 text-blue-700 rounded-lg">
                        <Bot size={20} />
                    </div>
                    <div>
                        <CardTitle className="text-xl">AI Summary</CardTitle>
                        <CardDescription>
                            Key takeaways generated by {modelUsed}
                        </CardDescription>
                    </div>
                </div>
            </CardHeader>
            <CardContent className="pt-6">
                <ul className="space-y-4">
                    {bullets.map((bullet, idx) => (
                        <li key={idx} className="flex gap-3 text-slate-700 leading-relaxed">
                            <ChevronRight className="w-5 h-5 text-blue-500 flex-shrink-0 mt-0.5" />
                            <span>{bullet}</span>
                        </li>
                    ))}
                </ul>
                {rawSummary && (
                    <div className="mt-8 pt-6 border-t border-slate-100">
                        <div className="flex items-center gap-2 text-slate-500 mb-2">
                            <FileText size={16} />
                            <span className="text-sm font-medium uppercase tracking-wider">
                                Full Paragraph Summary
                            </span>
                        </div>
                        <p className="text-sm text-slate-600 leading-relaxed italic">
                            &quot;{rawSummary}&quot;
                        </p>
                    </div>
                )}
            </CardContent>
        </Card>
    );
}
